{% set name = "pylint-django" %}
{% set version = "2.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pylint_django-{{ version }}.tar.gz
  sha256: 2f339e4bf55776958283395c5139c37700c91bd5ef1d8251ef6ac88b5abbba9b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core >1.0.0
    - pip
  run:
    - python >=3.7,<4.0
    - pylint-plugin-utils >=0.8
    - pylint >=2.0,<4.0
    - django >2.2

test:
  imports:
    - pylint_django
    - pylint_django.augmentations
    - pylint_django.checkers
    - pylint_django.transforms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PyCQA/pylint-django
  summary: A Pylint plugin to help Pylint understand the Django web framework
  license: GPL-2.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anthchirp
    - rxm7706
    - jakirkham
