{% set name = "pylint-django" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pylint-django-{{ version }}.tar.gz
  sha256: 9c324bf1734b0bae7693fa92ee6f486f35665a3519e5344bce0aa5f5743bd6f2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - django
    - pylint >=2.0
    # although the upstream package strictly only has a dependence on v0.5
    # pylint-plugin-utils, it can only run with pylint >=2.4 with v0.6
    - pylint-plugin-utils >=0.6
    - python >=3.6

test:
  imports:
    - pylint_django
    - pylint_django.augmentations
    - pylint_django.checkers
    - pylint_django.transforms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PyCQA/pylint-django
  summary: A Pylint plugin to help Pylint understand the Django web framework
  license: GPL-2.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anthchirp
    - jakirkham
