{% set name = "pylint-django" %}
{% set version = "2.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pylint_django-{{ version }}.tar.gz
  sha256: d167b1437342543727925a98c0dee9c8de8e8e1f8cb8caf868018febd2c4e2b7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core >1.0.0
    - pip
  run:
    - python >=3.7,<4.0
    - pylint-plugin-utils >=0.8
    - pylint >=2.0,<4.0
  run_constrained:
    - django >2.2

test:
  imports:
    - pylint_django
    - pylint_django.augmentations
    - pylint_django.checkers
    - pylint_django.transforms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PyCQA/pylint-django
  summary: A Pylint plugin to help Pylint understand the Django web framework
  license: GPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anthchirp
    - jakirkham
