{% set name = "pylint-django" %}
{% set version = "2.0.7" %}
{% set sha256 = "4689dd6e9e392528e00ee13983f06ef489dd46bdda124a4176dae5a9096434d0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.5
    - pip

  run:
    - python >=3.5
    - django
    - pylint-plugin-utils >=0.2.1
    - pylint >=1.8.2

test:
  imports:
    - pylint_django
    - pylint_django.augmentations
    - pylint_django.checkers
    - pylint_django.transforms

about:
  home: https://github.com/PyCQA/pylint-django
  license: GPL 2
  license_file: LICENSE
  summary: A Pylint plugin to help Pylint understand the Django web framework

extra:
  recipe-maintainers:
    - jakirkham
